services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      traefik.enable: true
      traefik.host: whoami
      traefik.http.routers.whoami.service: whoami
      # traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.services.whoami.loadbalancer.server.port: 80
    networks:
        - traefik-network
networks:
  traefik-network:
    external: true
